### ISSUE TITLE
More intuitive page navigation

### ISSUE THREAD

**Issue by alzafacon** [luiswoohoo/movie_search_test#1]
Page navigation between `My Watchlist` and `Search for movies` is unintuitive.

It's hard to tell that the text is a link/button.

Maybe tabs could help navigation be more clear.
or something like this:

![](https://usabilitygeek.com/wp-content/uploads/2019/05/03-UI-Patterns-Yummly.gif)

**Comment by luiswoohoo** [comment]
Turned the links into buttons. Probably not what you were thinking @alzafacon, but hopefully it's a little more clear.
